name: apptracker
description: A pharmacy stock tracking app (Sprints 1 & 2, mock data)
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.5.2
  connectivity_plus: ^5.0.2
  flutter_slidable: ^3.0.0
  sensors_plus: ^3.0.0
  fl_chart: ^0.66.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.1.2
  firebase_analytics: ^10.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true 